apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:

  service.webhook.devlake: |
    url: http://host.minikube.internal:4000/api/rest/plugins/webhook/connections/2/deployments
    headers:
      - name: Content-Type
        value: application/json
      - name: Authorization
        value: Bearer {{.secrets.devlake-token}}

  template.deployment-success: |
    webhook:
      devlake:
        method: POST
        body: |
          {
            "id": "{{.app.metadata.name}}-{{.app.status.sync.revision}}",
            "startedDate": "{{.app.status.operationState.startedAt}}",
            "finishedDate": "{{.app.status.operationState.finishedAt}}",
            "result": "SUCCESS",
            "environment": "{{.app.spec.destination.namespace}}",
            "displayTitle": "Deployment Success",
            "name": "{{.app.metadata.name}}",
            "deploymentCommits":[
              {
                "repoUrl": "{{.app.spec.source.repoURL}}",
                "commitSha": "{{.app.status.sync.revision}}",
                "result": "SUCCESS"
              }
            ]
          }

  template.deployment-failed: |
    webhook:
      devlake:
        method: POST
        body: |
          {
            "id": "{{.app.metadata.name}}-{{.app.status.sync.revision}}",
            "startedDate": "{{.app.status.operationState.startedAt}}",
            "finishedDate": "{{.app.status.operationState.finishedAt}}",
            "result": "FAILURE",
            "environment": "{{.app.spec.destination.namespace}}",
            "displayTitle": "Deployment Failed",
            "name": "{{.app.metadata.name}}",
            "deploymentCommits":[
              {
                "repoUrl": "{{.app.spec.source.repoURL}}",
                "commitSha": "{{.app.status.sync.revision}}",
                "result": "FAILURE"
              }
            ]
          }

  trigger.on-sync-succeeded: |
    when: app.status.operationState.phase in ['Succeeded']
    send: [deployment-success]

  trigger.on-sync-failed: |
    when: app.status.operationState.phase in ['Failed', 'Error']
    send: [deployment-failed]