apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  devlake-token: dGypXF96cmL2uRl2OI7gdp7a5anGBGOgWcFokh7lK7n4aPQYXFg1Xzlq0IUZedPywUPKWEYMRvwknemjCyFDaT2ELEJ8XTM7ZatpVQZfizDP5Vk4xl5rVon442wICdYG